### ISSUE TITLE
composer install on project does not create autoload files for subpackage

### ISSUE THREAD

**Issue by sebastiaandegeus** [composer/installers#188] opened 2014-09-25 15:19 UTC
I made a WP plugin as a composer package and tried to use the autoloader functionality by composer. This all works well if I do a `composer install` in the plugin directory because the autoloader files are created and I can `require vendor/autoload.php` just fine in my main plugin file. 

```
 "autoload": {
    "psr-4": {"ExamplePlugin\\": "src/"}
}
```

But when I put this plugin as a package in a project composer file the plugin ends up in: `web/app/plugins/example-plugin` because of the `installer-paths`. That's great. Works perfectly.

But the autoloading files were not generated because composer only generates it for the main `composer.json` which means the plugin will be broken because none of the internal classes will be loaded correctly.

I hope I explained it well.

**Comment by jajouka79** [comment] 2015-07-25 12:37
any answer to this? composer install on root is not adding the autoloaders for dependencies of dependencies

**Comment by kazitanvirahsan** [comment] 2015-09-10 10:02
This is a real problem.

**Comment by paul-m** [comment] 2015-11-19 21:12
I can't repro this.

In my case, it's `mile23/page-example`, which is a test/demo of using Drupal 8 with Composer. It requires `crell/api-problem`.

When I say `composer require mile23/page-example` the installer does everything it should, and then also generates a PSR-4 autoloader which includes Crell's api-problem namespace.

You should have a project vendor directory, and your code should include or require `vendor/autoload.php`.

**Comment by Cryt1c** [comment] 2018-02-15 23:44
Is this already fixed? I have the same problem. I have a php library which includes some helper functions:
```  "autoload": {
    "files": [
      "src/helpers/ethereum-client-workaround-helpers.php"
    ],
    "psr-4": {
      "Ethereum\\": "src/"
    }
  }````
But they won't appear in the autoload_files.php files, even if I do a "composer dump".
Any ideas how to fix this?

**Comment by crirus** [comment] 2018-03-14 10:23
Facing the same issue, no solution?

**Comment by mopsyd** [comment] 2018-03-31 17:37
I had a similar issue with a wordpress theme I was building recently. Do the following:

- Initialize your theme/plugin with it's own composer file, map from a subdirectory to vendor if you don't want the composer.json in your plugin root.

- Make sure you upload the `autoload.php` file AND the composer folder in vendor. The actual autoload maps that get generated live in there. The autoload.php is just a proxy to that, and it doesn't work without them.

**Comment by MarkMurphy** [comment] 2018-07-05 14:07
It appears that `vendor/composer/installed.json` isn't adding `"files": [...]` for the related package.

**Comment by brandonbest** [comment] 2018-08-02 15:36
This was a very annoying issue. Found this and it helped:
https://stackoverflow.com/questions/18106599/composer-does-not-generate-autoloader-information-autoload-namespaces-php

**Comment by Seldaek** [comment] 2022-03-18 12:18
Closing as I don't really see what the problem is here. If someone still has the issue please post detailed reproduction instructions otherwise there's not much we can do.

**Closed by Seldaek** 2022-03-18 12:18 UTC
