### ISSUE TITLE
wordpress-plugin and wordpress-theme types throw errors with path repositories

### ISSUE THREAD

**Issue by joshdaws** [composer/installers#267] opened 2015-10-19 23:45 UTC
I'm trying to use a repository of type `path` with a local package of type `wordpress-plugin`.  I get the following error:

`[InvalidArgumentException]                                                   
  $from (web/app/themes/acf-pro/) and $to (/Users/dawsj028/www/tm-plugins/adv  
  anced-custom-fields-pro) must be absolute paths. `

If I remove the type attribute from composer.json it installs to the vendor directory as expected. Any ideas?

**Comment by johnnytrinh** [comment] 2015-10-20 12:22
Can you paste the entire composer.json file? is there a copy mistake for the ACF plugin since there is a space in 'advanced'?

**Comment by joshdaws** [comment] 2015-10-20 13:32
That was a paste error.  Here's the project composer.json:

`
{
  "name": "roots/bedrock",
  "type": "project",
  "config": {
    "preferred-install": "dist"
  },
  "repositories": [
    {
      "type": "composer",
      "url": "http://wpackagist.org"
    },
    {
        "type": "path",
        "url": "/Users/dawsj028/www/tm-plugins/*"
    }
    
  ],
  "require": {
    "php": ">=5.5",
    "composer/installers": "~1.0.21",
    "vlucas/phpdotenv": "^2.0.1",
    "johnpbloch/wordpress": "4.3.1",
    "wpackagist-plugin/advanced-custom-fields": "dev-trunk",
    "tm-plugins/acf-pro": "*@dev"
  },
  "extra": {
    "installer-paths": {
      "web/app/mu-plugins/{$name}/": ["type:wordpress-muplugin"],
      "web/app/plugins/{$name}/": ["type:wordpress-plugin"],
      "web/app/themes/{$name}/": ["type:wordpress-theme"]
    },
    "wordpress-install-dir": "web/wp"
  }
}
`

And here's the package json:

`{
  "name": "tm-plugins/acf-pro",
  "description": "Advanced Custom Fields Pro",
  "type": "wordpress-plugin",
  "require": {
    "php": ">=5.5",
    "composer/installers": "~1.0.21"
  }
}`

**Comment by joshdaws** [comment] 2015-10-20 16:04
I tried a few other package types.  It seems to be a universal issue with installers and path repositories.

**Comment by joshdaws** [comment] 2015-12-02 23:12
I've created a pull request to fix this issue.  https://github.com/composer/installers/pull/272

**Comment by dzuelke** [comment] 2016-04-10 20:36
The fix in #272 is wrong. The issue is the trailing slashes in your installer paths. If you remove them, the symlink succeeds.

**Comment by Seldaek** [comment] 2016-04-11 12:16
Closed by https://github.com/composer/composer/pull/5164

**Closed by Seldaek** 2016-04-11 12:16 UTC
